# Configuración global para WordPress Deploy Tools
# Este es un archivo de ejemplo. Copia a config.yaml y personaliza.
# 
# NOTA IMPORTANTE: Este archivo contiene solo configuración global que
# se aplica a todos los sitios. Para configurar sitios específicos,
# utilice el archivo sites.yaml.
#
# Flujo de trabajo con múltiples sitios:
# 1. Configuración global aquí en config.yaml
# 2. Sitios específicos en sites.yaml
# 3. Para usar: python cli.py [comando] --site [alias-sitio]

# Ajustes WP-CLI globales
wp_cli:
  memory_limit: "512M"  # Límite de memoria para PHP en WP-CLI

# Parámetros de seguridad por defecto
security:
  production_safety: "enabled"  # Protección contra sobrescritura en producción
  backups: "enabled"  # Crear backups automáticos antes de operaciones peligrosas

# Exclusiones por defecto (se pueden sobrescribir por sitio)
exclusions:
  # Directorios de caché y optimización
  cache: "wp-content/cache/"
  litespeed: "wp-content/litespeed/"
  jetpack-waf: "wp-content/jetpack-waf/"
  wflogs: "wp-content/wflogs/"
  
  # Archivos de caché y configuración
  object-cache: "wp-content/object-cache.php"
  
  # Plugins de caché y optimización
  akismet: "wp-content/plugins/akismet/"
  wordfence: "wp-content/plugins/wordfence/"
  litespeed-cache: "wp-content/plugins/litespeed-cache/"
  
  # Media (por defecto no sincronizar uploads)
  default-themes: "wp-content/themes/twenty*"
  uploads-by-year: "wp-content/uploads/[0-9][0-9][0-9][0-9]/"

  # Debug y desarrollo
  debug-logs: "wp-content/debug.log*"

# Archivos protegidos por defecto
protected_files:
  - "wp-config.php"
  - "wp-config-ddev.php"
  - ".gitignore"
  - ".ddev/"

# -------------------------------------------------------------------------
# EJEMPLO DE CONFIGURACIÓN DE SITIO (para sites.yaml)
# Este es un ejemplo de cómo debería verse su sites.yaml
# -------------------------------------------------------------------------
#
# default: "ejemplo-sitio"  # Sitio predeterminado (opcional)
#
# sites:
#   ejemplo-sitio:
#     ssh:
#       remote_host: "example-host"  # Alias SSH en ~/.ssh/config
#       remote_path: "/path/to/remote/wordpress/"
#       local_path: "/path/to/local/wordpress/"
#
#     urls:
#       remote: "https://www.example.com"
#       local: "https://local.example.test"
#
#     database:
#       remote:
#         name: "db_name"
#         user: "db_user"
#         password: "db_password"
#         host: "localhost"
#
#     media:
#       url: "https://www.example.com/wp-content/uploads/"
#       expert_mode: false
#       path: "../media"
#
#     ddev:
#       webroot: "/var/www/html/app/public" 