# Global configuration for WordPress Deploy Tools
# This is an example file. Copy to config.yaml and customize.
# 
# IMPORTANT NOTE: This file contains only global configuration that
# applies to all sites. For site-specific configuration,
# use the sites.yaml file.
#
# Configuration recommendations:
# 1. Global configuration here in config.yaml
# 2. Site-specific configuration in sites.yaml
# 3. For use: python cli.py [command] --site [site-alias]

# WP-CLI configuration
wp_cli:
  memory_limit: "512M"  # PHP memory limit for WP-CLI operations

# Security configuration
security:
  production_safety: "enabled"  # Protection against accidentally overwriting production
  backups: "enabled"  # Always create backups before critical operations

# Patch and synchronization configuration
sync:
  allow_empty_diff: true  # Allow continuing even with empty diff (CURRENTLY IGNORED)
  allow_deletions: false  # Whether to allow deletions during synchronization (dangerous) (CURRENTLY IGNORED)
  check_conflicts: true   # Always check for conflicts with local changes (CURRENTLY IGNORED)

# Default exclusions (are merged with site-specific exclusions)
exclusions:
  # Cache and optimization directories
  litespeed: "wp-content/litespeed/*"
  cache: "wp-content/cache/*"
  wpsc-cache: "wp-content/wp-super-cache/*"
  w3c: "wp-content/w3tc-cache/*"
  
  # Cache and configuration files
  autoptimize: "wp-content/autoptimize/*"
  
  # Security plugins (to avoid conflicts)
  wordfence: "wp-content/wflogs/*"
  
  # Logs and temporary files
  debug.log: "wp-content/debug.log"
  debug: "wp-content/debug/*"
  
  # Backup files
  backup_files: "**/*.bak"

# Protected files by default
protected_files:
  - "wp-config.php"
  - "wp-config-ddev.php"
  - ".gitignore"
  - ".ddev/**/*"
  - "wp-content/plugins/wp-original-media-path/"

# -------------------------------------------------------------------------
# EXAMPLE SITE CONFIGURATION (for sites.yaml)
# This is an example of how your sites.yaml should look like
# -------------------------------------------------------------------------
#
# default: "ejemplo-sitio"  # Default site (optional)
#
# sites:
#   ejemplo-sitio:
#     ssh:
#       remote_host: "example-host"  # SSH alias in ~/.ssh/config
#       remote_path: "/path/to/remote/wordpress/"
#       local_path: "/path/to/local/wordpress/"
#
#     urls:
#       remote: "https://www.example.com"
#       local: "https://local.example.test"
#
#     database:
#       remote:
#         name: "db_name"
#         user: "db_user"
#         password: "db_password"
#         host: "localhost"
#
#     media:
#       url: "https://www.example.com/wp-content/uploads/"
#       expert_mode: false
#       path: "../media"
#
#     ddev:
#       webroot: "/var/www/html/app/public" 